seed_everything: 42

model:
  class_path: pose_estimation.pl_wrappers.egoposeformer.PoseHeatmapMVFEXLightningModel
  init_args:
    model_cfg:
      num_heatmap: 15
      num_joints: 16
      num_views: 4
      camera_model: ego4view_syn
      image_size:
        - 256
        - 256
      feat_down_stride: 4
      heatmap_threshold: 0.5
      anchor_2d_update: True
      encoder_cfg:
        resnet_cfg:
          model_name: resnet18
          out_stride: 4
          use_imagenet_pretrain: True
        neck_cfg:
          in_channels:
            - 64
            - 128
            - 256
            - 512
          out_channels: 128
      mvf_cfg:
        input_dims: 128
        embed_dims: 256
        num_former_layers: 1
        joint_query_adaptation: True
        mvf_transformer_cfg:
          cross_attn_cfg:
            num_heads: 4
            batch_first: True
          spatial_attn_cfg:
            num_heads: 4
            batch_first: True
          ffn_cfg:
            feedforward_dims: 512
            num_fcs: 2
            ffn_drop: 0.0

    dataset_type: ego4view_syn_heatmap_mvf
    dataset_kwargs: {
      camera_pos: all
    }
    data_root: /CT/Ego4View/static00/Ego4View_syn
    lr: 0.001
    weight_decay: 0.005
    lr_decay_epochs:
      - 8
      - 10
    warmup_iters: 500
    w_heatmap: 10.0
    batch_size: 64
    workers: 16
    compile: True
    compile_mode: default
    save_result: False
    heatmap_estimator_pretrained_stereo_front: ./logs/ego4view_syn_heatmap_stereo_front/lightning_logs/version_0/checkpoints/epoch=11.ckpt
    heatmap_estimator_pretrained_stereo_back: ./logs/ego4view_syn_heatmap_stereo_back/lightning_logs/version_0/checkpoints/epoch=11.ckpt

trainer:
  max_epochs: 12
  check_val_every_n_epoch: 1
  log_every_n_steps: 400
  devices: 1
  benchmark: true
  precision: 32
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm
  callbacks:
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 400
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        save_top_k: -1
        filename: '{epoch}'
  logger:
    - class_path: pytorch_lightning.loggers.CSVLogger
      init_args:
        save_dir: ./logs/ego4view_syn_heatmap_mvfex-n1_jqa